### PR TITLE
update commit convention

### LINKED ISSUE #9: Updating commit convention
Instead of fixes into every commit: "fixes #XX" in the PR description and we'd like to use "issue #XX" in the individual commits since the PR as a whole fixes the issue.

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
Fixes Issue #9

### CODE REVIEW

**Review by k-allagbe — APPROVED** [review]

**Comment by Francois-Werbrouck** [comment]
All our commits should now look like:' Issue #9: update commit template'

**Review by SonOfLope — APPROVED** [review]

**Review by MaxenceGui — APPROVED** [review]

**Review by JolanThomassin — APPROVED** [review]

**Comment by rngadam** [comment]
@Francois-Werbrouck also should add a note to put Fixes #XX in the description of the pull request (if indeed the PR as a whole is expected to fix the issue)

**Review by rngadam — CHANGES_REQUESTED** [review]
@Francois-Werbrouck also should add a note to put Fixes #XX in the description of the pull request (if indeed the PR as a whole is expected to fix the issue)

**Comment by rngadam** [comment]
> @Francois-Werbrouck also should add a note to put Fixes #XX in the description of the pull request (if indeed the PR as a whole is expected to fix the issue)

still waiting on the updated doc to approve

@Francois-Werbrouck

**Review by elwoujdi — APPROVED** [review]

**Pull request merged**
